### ISSUE TITLE
Repo name (README.md)

### ISSUE THREAD

**Issue by bestwhale777** [masa-finance/masa-node-v1.0#1]
From README.md
Install The Masa Testnet Node v1.0
```
git clone https://github.com/masa-finance/masa-node-v1
cd masa-node-v1
```

Please fix:
```
git clone https://github.com/masa-finance/masa-node-v1.0.git
cd masa-node-v1.0
```

**Comment by Mikenificent** [comment]
Also: 
`cd masa-node-v1
PRIVATE_CONFIG=ignore docker-compose up -d`

To:
`cd masa-node-v1.0
PRIVATE_CONFIG=ignore docker-compose up -d`

**Comment by teslashibe** [comment]
Fixed. Thanks
