### ISSUE TITLE
Request for bootnode deployment and operations.

### ISSUE THREAD

**Issue by setar** [masa-finance/masa-node-v1.0#11]
I am ready to deploy the bootnode as I have personal hardware server cluster based in data center in Saint-Petersburg (Russia)

**Comment by teslashibe** [comment]
@setar thank you - it would be great if you an run a bootnode - please submit a PR to add it to the readme when you have it up and running. 

Add it to the community section of the Readme. 

Many thanks!

**Comment by teslashibe** [comment]
@setar please submit a PR with a `feature/` branch to the next release branch here: https://github.com/masa-finance/masa-node-v1.0/tree/v1.02
