### ISSUE TITLE
Cant start UI container 

### ISSUE THREAD

**Issue by deepminimal** [masa-finance/masa-node-v1.0#18]
Hello! 
1. PRIVATE_CONFIG=ignore docker-compose up -d ui 
2. docker logs masa-node-v10_ui_1
3. `standard_init_linux.go:228: exec user process caused: exec format error`

uname -a
`Linux Ubuntu-2110-impish-amd64-base 5.13.0-21-generic #21-Ubuntu SMP Tue Oct 19 08:59:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

docker version
```
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:41 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

cat /etc/os-release
```
PRETTY_NAME="Ubuntu 21.10"
NAME="Ubuntu"
VERSION_ID="21.10"
VERSION="21.10 (Impish Indri)"
```

docker-compose version
```
docker-compose version 1.27.4, build unknown
docker-py version: 4.4.4
CPython version: 3.9.7
OpenSSL version: OpenSSL 1.1.1l  24 Aug 2021
```

docker image ls
```
REPOSITORY                 TAG       IMAGE ID       CREATED       SIZE
hideonbushx/node-ui        latest    9429770f1aa3   2 weeks ago   1.47GB
```

**Comment by usrbad** [comment]
the same here

**Comment by usrbad** [comment]
`docker-compose ps`
```          Name                         Command                  State                                                    Ports
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
masa-node-v10_masa-node_1   /bin/sh -c DDIR=/qdata/dd        Up (healthy)   21000/tcp, 30303/tcp, 30303/udp, 50400/tcp, 0.0.0.0:22001->8545/tcp,:::22001->8545/tcp, 8546/tcp
                             ...
masa-node-v10_ui_1          docker-entrypoint.sh npm start   Exit 1

**Comment by usrbad** [comment]
```
#$ docker logs masa-node-v10_ui_1
standard_init_linux.go:228: exec user process caused: exec format error

**Comment by MemberIT** [comment]
@teslashibe 
https://hub.docker.com/layers/hideonbushx/node-ui/latest/images/sha256-ed027a9aa4b9fa2b46ad0f0c3cc49fcb8fdc7e867d69ca5685aff7f63f26d1f3?context=explore
Image available only linux/arm64 for Mac on M1. Need an image linux/amd64 (x86_64). Please build image.

**Comment by hi044** [comment]
hi @MemberIT 
I don't get your comment, i'm sorry. what should i do to fix this issue? I also have ubuntu

**Comment by teslashibe** [comment]
@hide-on-bush-x @Luka-Loncar this also links to #17

**Comment by teslashibe** [comment]
@hide-on-bush-x please to the PR and close this out when you merge to the Node UI repo - thanks

**Comment by hide-on-bush-x** [comment]
@deepminimal @usrbad @hi044 @MemberIT 
Hello guys, there is a possible fix in this branch, feel free to take a look
https://github.com/masa-finance/masa-node-v1.0/tree/v1.03

**Comment by deepminimal** [comment]
@hide-on-bush-x Hello! thanks its work. 
![image](https://user-images.githubusercontent.com/18044597/156378296-596ef4d7-a327-49f5-b58f-0d0d1495ec02.png)

**Comment by MemberIT** [comment]
@hide-on-bush-x It's worked for me to
