### ISSUE TITLE
geth run guide

### ISSUE THREAD

**Issue by maxzonder** [masa-finance/masa-node-v1.0#2]
Initialize the node
In the node directory, initialize the first node:

`geth --datadir data init ../network/genesis.json`

must be 

../network/testnet/genesis.json

**Comment by teslashibe** [comment]
@maxzonder good catch - thank you! We will update in the next release and consolidate the genesis file into one location. You can view this on the new release branch

**Comment by teslashibe** [comment]
This has been included in this branch: https://github.com/masa-finance/masa-node-v1.0/tree/v1.02
