### ISSUE TITLE
How can i change port http://localhost:3000/ to another

### ISSUE THREAD

**Issue by Samuellle** [masa-finance/masa-node-v1.0#30]
Hello! I have installed node Taraxa and Taraxa has already use port http://localhost:3000/. 
In this way when i have installed Masa-finance, i have an error "Bind for 0.0.0.0:3000 failed: port is already allocated
ERROR: for ui  Cannot start service ui: driver failed programming external connectivity on endpoint masa-node-v10_ui_1 (dcbc12fcdca8679aa4d7ac6d288a81691aabf281cc5b0f5d1d7cfe45f1acd8bc): Bind for 0.0.0.0:3000 failed: port is already allocated"

What i gone do?

**Comment by deepminimal** [comment]
@Samuellle Hello!
Here you can change port like 3001:3000
https://github.com/masa-finance/masa-node-v1.0/blob/main/src/ui/docker-compose.yml#L6

**Comment by Samuellle** [comment]
It works! Thanx!
