### ISSUE TITLE
ADD to .gitignore (.DS_Store)

### ISSUE THREAD

**Issue by yurydev84** [masa-finance/masa-node-v1.0#6]
Add to .gitignore file (MacOS file):
`.DS_Store`

**Comment by setar** [comment]
https://github.com/masa-finance/masa-node-v1.0/pulls#:~:text=ago%20by%20myuriy-,Remove%20Mac%20OSX%20DS_Store%20directory%20index%20from%20repo,-%234%20opened%201

**Comment by yurydev84** [comment]
> #4

good job!

**Comment by teslashibe** [comment]
Fixed
