### ISSUE TITLE
not build from source

### ISSUE THREAD

**Issue by setar** [masa-finance/masa-node-v1.0#9]
Clean install ubuntu 20.4 LTS & full update
GO v1.17.5
bb1d84288645fd67dc24198d27cdeb7e1f31e9fd
~/masa-node-v1.0/src$ make all
break build with error:
```
signer/core/api.go:29:2: no required module provides package github.com/ethereum/go-ethereum/accounts/keystore; to add it:
        go get github.com/ethereum/go-ethereum/accounts/keystore
util.go:47: exit status 1
exit status 1
make: *** [Makefile:26: all] Error 1
```
go get github.com/ethereum/go-ethereum/accounts/keystore - not work, 
go get github.com/ethereum/go-ethereum - also not fix the error

P.S. 
GO v1.17.1 - give same error

**Comment by teslashibe** [comment]
@setar this should be fixed in the latest release now.
